### ISSUE TITLE
Using Email templates

### ISSUE THREAD

**Issue by deresegetachew** [jacoborus/curlymail#2]
Hi there;

is it possible to use email templates like https://github.com/mailgun/transactional-email-templates with curlymail? 

would it also be possible to provide a path rather than a string @ the html attribute of the template definition.

**Comment by jacoborus** [comment]
> is it possible to use email templates like https://github.com/mailgun/transactional-email-templates with curlymail?

yes, but if you want to use variables in those templates you will have to add them by yourself

> would it also be possible to provide a path rather than a string @ the html attribute of the template definition.

Nope, but you can pass a `fs.writeFileSync('path/to/your/template.html')`
